services:

#############
# PORTAINER #
#############
  portainer:
    image: portainer/portainer-ce:sts
    container_name: mgnt-portainer
    restart: ${RESTART_POLICY}
    volumes:
      - "${DOCKER_SOCKET}:/var/run/docker.sock"
      - "./data/portainer:/data"
    ports:
      - ${PORTAINER_PORT_SSL}:9443
      - ${PORTAINER_PORT_UI}:8000
    networks:
      - locMgnt

###########
# PI-HOLE #
###########
  pihole:
    image: pihole/pihole:latest
    container_name: mgnt-pihole
    hostname: dckvm-piHole
    restart: ${RESTART_POLICY}
    env_file: .env
    volumes:
      - "./data/pihole/etc-pihole:/etc/pihole"
      - "./data/pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
      - "./data/pihole/dnsmasq-leases:/var/lib/misc"
    cap_add:
      - NET_ADMIN
    dns:
      - ${DNS01}
      - ${DNS02}
    environment:
      - DNS1=${DNS01}
      - DNS2=${DNS02}
      - ServerIP=${PIHOLE_IP}
      - DNSMASQ_LISTENING=all
      - WEBPASSWORD=${PIHOLE_PASS}
      - TZ= ${TZ}
      - mac-address=${PIHOLE_MAC}
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    networks:
      mainLan:
        ipv4_address: ${PIHOLE_IP}
#      iotVlan:
#        ipv4_address: ${PIHOLE_IOT_IP}

#################
# HomeAssistant #
#################
  homeassistant:
#    image: homeassistant/raspberrypi4-homeassistant:latest
    image: homeassistant/home-assistant:latest
    container_name: mgnt-homeassistant
    hostname: dckvm-homeassistant
    restart: ${RESTART_POLICY}
    env_file: .env
    volumes:
      - "./data/homeassistant:/config"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      mainLan:
        ipv4_address: ${HA_MAIN_IP}

volumes:
  data:

networks:
  locMgnt:
    driver: bridge
# MainLAN
  mainLan:
    name: mainLan
    driver: macvlan
    driver_opts:
      parent: ${NET_INT}
    ipam:
      config:
        - subnet: ${IP_SUB}
          gateway: ${IP_GAT}
# IOT VLAN - id 666
  iotVlan:
    name: iotVlan
    driver: macvlan
    driver_opts:
      parent: ${NET_INT}.666
    ipam:
      config:
        - subnet: ${IOT_SUB}
          gateway: ${IOT_GAT}
