version: "3.9"

services:

#############
# PORTAINER #
#############
  portainer:
    image: portainer/portainer-ce
    container_name: mgnt-portainer
    restart: ${RESTART_POLICY}
    volumes:
      - "${DOCKER_SOCKET}:/var/run/docker.sock"
      - "./data/portainer:/data"
    ports:
      - ${PORTAINER_PORT_UI}:9000
      - ${PORTAINER_PORT_SSL}:8000
    expose:
      - ${PORTAINER_PORT_UI}
      - ${PORTAINER_PORT_SSL}
    networks:
      - locMgnt

###########
# PI-HOLE #
###########
  pihole:
    image: pihole/pihole:latest
    container_name: mgnt-pihole
    hostname: dckvm-piHole
    restart: ${RESTART_POLICY}
    env_file: .env
    volumes:
      - "./data/pihole/etc-pihole:/etc/pihole"
      - "./data/pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
      - "./data/pihole/dnsmasq-leases:/var/lib/misc"
    cap_add:
      - NET_ADMIN
    dns:
      - ${DNS01}
      - ${DNS02}
    environment:
      - DNS1=${DNS01}
      - DNS2=${DNS02}
      - ServerIP=${PIHOLE_IP}
      - DNSMASQ_LISTENING=all
      - WEBPASSWORD=${PIHOLE_PASS}
      - TZ= ${TZ}
      - mac-address=${PIHOLE_MAC}
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    networks:
      mainLan:
        ipv4_address: ${PIHOLE_IP}
#      iotVlan:
#        ipv4_address: ${PIHOLE_IOT_IP}

#################
# HomeAssistant #
#################
  homeassistant:
    image: homeassistant/raspberrypi4-homeassistant:latest
    container_name: mgnt-homeassistant
    hostname: dckvm-homeassistant
    restart: ${RESTART_POLICY}
    env_file: .env
    volumes:
      - "./data/homeassistant:/config"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      mainLan:
        ipv4_address: ${HA_MAIN_IP}

##########
# MYSQL #
#########
  mgnt-mysql:
    image: mysql:8.0
    container_name: mgnt-mysql
    command: --sql-mode=""
    restart: ${RESTART_POLICY}
    ports:
      - "3306"
    volumes:
      - "./data/mysql:/var/lib/mysql"
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${LIBRENMS_ROOT_PASS}
      - MYSQL_USER=${LIBRENMS_DB_USER}
      - MYSQL_PASSWORD=${LIBRENMS_DB_PASS}
      - MYSQL_DATABASE=${LIBRENMS_DB_NAME}
    healthcheck:
      test: "mysql -h localhost -u root -p$$MYSQL_ROOT_PASSWORD -e 'USE librenms'"
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      mainLan:
        ipv4_address: ${MYSQL_IP}

#########
# REDIS #
#########
  mgnt-redis:
    image: redis:7.2-alpine
    container_name: mgnt-redis
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: ${RESTART_POLICY}
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
      - "./redis.conf:/usr/local/etc/redis/redis.conf:ro"
    environment:
      - TZ=${TZ}
    networks:
      mainLan:
        ipv4_address: ${REDIS_IP}

#################
# LIBRENMS CORE #
#################
  mgnt-librenms:
    image: librenms/librenms:latest
    container_name: mgnt-librenms
    hostname: dckvm-librenms
    restart: ${RESTART_POLICY}
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - DB_HOST=${MYSQL_IP}
      - DB_NAME=${LIBRENMS_DB_NAME}
      - DB_USERNAME=${LIBRENMS_DB_USER}
      - DB_PASSWORD=${LIBRENMS_DB_PASS}
      - SIDECAR_DISPATCHER=1
      - SIDECAR_SNMPTRAPD=1
      - POLLERS=16
      - BASE_URL=${APP_URL}
      - DAILY_ON_STARTUP=true
      - APP_KEY=${APP_KEY}
    volumes:
      - "./data/libreNMS/:/data"
    env_file:
      - "./librenms.env"
    networks:
      mainLan:
        ipv4_address: ${LIBRENMS_IP}
    ports:
      - target: ${LIBRENMS_PORT}
        published: ${LIBRENMS_PORT}
        protocol: tcp
    links:
      - mgnt-mysql:db
    depends_on:
      mgnt-mysql:
        condition: service_healthy

##############
# DISPATCHER #
##############
  mgnt-dispatcher:
    image: librenms/librenms:latest
    container_name: mgnt-dispatcher
    hostname: dckvm-dispatcher
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - mgnt-librenms
      - mgnt-redis
    volumes:
      - "./data/libreNMS/:/data"
    env_file:
      - "./librenms.env"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - DB_HOST=${MYSQL_IP}
      - DB_NAME=${LIBRENMS_DB_NAME}
      - DB_USERNAME=${LIBRENMS_DB_USER}
      - DB_PASSWORD=${LIBRENMS_DB_PASS}
      - DB_TIMEOUT=60
      - DISPATCHER_NODE_ID=dispatcher1
      - SIDECAR_DISPATCHER=1
    restart: ${RESTART_POLICY}

volumes:
  data:

networks:
  locMgnt:
    driver: bridge
# MainLAN
  mainLan:
    name: mainLan
    driver: macvlan
    driver_opts:
      parent: ${NET_INT}
    ipam:
      config:
        - subnet: ${IP_SUB}
          gateway: ${IP_GAT}
# IOT VLAN - id 666
  iotVlan:
    name: iotVlan
    driver: macvlan
    driver_opts:
      parent: ${NET_INT}.666
    ipam:
      config:
        - subnet: ${IOT_SUB}
          gateway: ${IOT_GAT}
